### ISSUE TITLE
Add option to filter https://tools.wmflabs.org/geohack/ URLs

### ISSUE THREAD

**Issue by shorty66** [guardianproject/LocationPrivacy#1]
The wikipedia links all coordinates to https://tools.wmflabs.org/geohack/. This is annoying when using an android device as the site needs to load, when really all the user wants to have is a geo: intent to use his favourite mapping app.
This is especially annoying if an offline wikipedia-viewer like "aard dictionary" or "kiwix" is used. While these apps do not need internet access, latter is needed to get the geo: uri on the wmflabs.org site in order to open that location in an offline mapping App like "OSMAnd".

I understand, that this app is able to intercept certain URLs containing geo information. It would be really nice, if this url type could be supported.

I do know that this particular problem is not really privacy related but the feature would be useful nonetheless.

**Comment by eighthave** [comment]
Good idea, thanks for that.  Wikipedia is also a good source for other map URLs to support.

**Comment by eighthave** [comment]
I moved this to the issue tracker that we use, since I'm going to turn off the github one:
https://dev.guardianproject.info/issues/4507
